name: The Basics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16559843346476555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.375
  lightness: 0.9201052957214415
  saturation: 0.13227528287097812
  rhythmicContrast: 0.33496960811316967
purpose: []
